In [113]:
from IPython.display import display

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)
plt.style.use('ggplot')

# Show matplotlib plots in this notebook
%matplotlib inline
# Setting plot parameters
from pylab import rcParams
params = {
    'figure.figsize': (8, 8),
    'legend.fontsize': 15
}
rcParams.update(params)

In [114]:
df = pd.read_csv('../private/results-04-10.csv')  # TODO: Write the response file

EXCHANGE_RATE = [
    1.0874,
    1.2070,
    1.3901,
    1.3108,
    1.3653,
    1.2576
]

In [115]:
def get_cad_salary(salary, term):
    return float(salary) * EXCHANGE_RATE[term-1]

In [116]:
def is_invalid_salary(salary):
    if type(salary) == str:
        salary = salary.replace(',', '')
    try:
        float(salary)
        if salary < 100:
            return True
        return False
    except:
        print 'exception', salary
        return True

In [117]:
def isnan(a):
    return a != a

In [118]:
def isfloat(value):
  try:
    float(value)
    return not isnan(value)
  except ValueError:
    return False

In [119]:
for i in range(0, df.shape[0]):
    print 'Row ' + str(i)
    for term in range(1, 7):
        if isnan(df['coop_loc_' + str(term)][i]) or 'USA' not in df['coop_loc_' + str(term)][i]:
            continue
        if is_invalid_salary(df['coop_salary_' + str(term)][i]):
            continue
        old = df['coop_salary_' + str(term)][i]
        if isnan(old):
            continue
            
        if not isfloat(old):
            old = old.replace(',', '')
        df.loc[i, 'coop_salary_' + str(term)] = get_cad_salary(old, term)
        print('  City: ' + df['coop_loc_' + str(term)][i] + 
              ' | From $' + str(old) + ' to $' + str(df['coop_salary_' + str(term)][i]))

Row 0
  City: Chicago, USA | From $8250.00 to $10725.0
  City: Mountain View, USA | From $12060.00 to $15678.0
  City: Chicago, USA | From $8000.00 to $10400.0
Row 1
  City: San Francisco, USA" | From $1248.00 to $1622.4
  City: Santa Clara, USA | From $11500.00 to $14950.0
Row 2
  City: Menlo Park, USA | From $6500.00 to $8450.0
  City: San Francisco, USA | From $5000.00 to $6500.0
  City: San Francisco, USA | From $8000.00 to $10400.0
Row 3
  City: Boston, USA | From $3000.00 to $3900.0
  City: San Mateo, USA | From $9500.00 to $12350.0
  City: Seattle, USA | From $5000.00 to $6500.0
Row 4
  City: San Francisco, USA | From $3200.00 to $4160.0
  City: San Francisco, USA | From $4000.00 to $5200.0
  City: Santa Clara, USA | From $8916.00 to $11590.8
  City: New York City, USA | From $2600.00 to $3380.0
  City: Seattle, USA | From $7150.00 to $9295.0
Row 5
  City: San Francisco, USA | From $4500.00 to $5850.0
Row 6
  City: Boston, USA | From $3500.00 to $4550.0
  City: Bellevue, USA | From $4200.00 to $5460.0
  City: Menlo Park, USA | From $11390.00 to $14807.0
  City: Sunnyvale, USA | From $9250.00 to $12025.0
Row 7
  City: San Mateo, USA | From $8750.00 to $11375.0
  City: San Francisco, USA | From $4500.00 to $5850.0
Row 8
  City: Foster City, USA | From $4000.00 to $5200.0
  City: San Francisco, USA | From $8515.00 to $11069.5
  City: New York City, USA | From $7360.00 to $9568.0
Row 9
  City: San Francisco, USA | From $7000.00 to $9100.0
  City: San Francisco, USA | From $8000.00 to $10400.0
Row 10
  City: San Francisco, USA | From $3500.00 to $4550.0
Row 11
  City: Mountain View, USA | From $3000.00 to $3900.0
  City: San Francisco, USA | From $10720.00 to $13936.0
  City: Seattle, USA | From $7200.00 to $9360.0
Row 12
  City: San Francisco, USA | From $3600.00 to $4680.0
  City: Seattle, USA | From $4500.00 to $5850.0
  City: San Francisco, USA | From $9000.00 to $11700.0
Row 13
  City: Weston, USA | From $2900.00 to $3770.0
  City: Menlo Park, USA | From $15600.00 to $20280.0
Row 14
  City: San Francisco, USA | From $9825.00 to $12772.5
  City: San Francisco, USA | From $8250.00 to $10725.0
  City: San Francisco, USA | From $6720.00 to $8736.0
Row 15
  City: San Francisco, USA | From $2800.00 to $3640.0
  City: San Francisco, USA | From $2000.00 to $2600.0
  City: San Francisco, USA | From $9000.00 to $11700.0
Row 16
  City: San Francisco, USA | From $2880.00 to $3744.0
  City: Santa Clara, USA | From $4480.00 to $5824.0
  City: Mountain View, USA | From $5712.50 to $7426.25
Row 17
  City: Venice, USA | From $6688.00 to $8694.4
  City: Mountain View, USA | From $8250.00 to $10725.0
Row 18
  City: San Francisco, USA | From $3500.00 to $4550.0
  City: San Francisco, USA | From $7000.00 to $9100.0
  City: San Francisco, USA | From $11685.00 to $15190.5
Row 19
  City: Palo Alto, USA | From $3200.00 to $4160.0
  City: San Francisco, USA | From $7300.00 to $9490.0
  City: Menlo Park, USA | From $6400.00 to $8320.0
Row 20
  City: Mountain View, USA | From $8500.00 to $11050.0
  City: San Francisco, USA | From $3400.00 to $4420.0
  City: San Francisco, USA | From $9862.00 to $12820.6
  City: Menlo Park, USA | From $7130.00 to $9269.0
Row 21
  City: San Francisco, USA | From $2500.00 to $3250.0
  City: San Francisco, USA | From $6400.00 to $8320.0
Row 22
  City: Toronto, USA | From $6400.00 to $8320.0
  City: San Francisco, USA | From $0.00 to $0.0
Row 23
  City: San Francisco, USA | From $4200.00 to $5460.0
  City: San Francisco, USA | From $6600.00 to $8580.0
  City: San Francisco, USA | From $10720.00 to $13936.0
  City: New York City, USA | From $7500.00 to $9750.0
Row 24
  City: San Mateo, USA | From $9000.00 to $11700.0
  City: San Francisco, USA | From $7200.00 to $9360.0
Row 25
  City: San Francisco, USA | From $5895.00 to $7663.5
  City: Menlo Park, USA | From $5550.00 to $7215.0
  City: Sunnyvale, USA | From $8000.00 to $10400.0
Row 26
  City: Seattle, USA | From $7200.00 to $9360.0
Row 27
  City: San Mateo, USA | From $6000.00 to $7800.0
  City: Menlo Park, USA | From $5000.00 to $6500.0
Row 28
  City: Sunnyvale, USA | From $9913.00 to $12886.9
Row 29
  City: Menlo Park, USA | From $10773.00 to $14004.9
  City: Redmond, USA | From $6080.00 to $7904.0
Row 30
  City: San Francisco, USA | From $10988.00 to $14284.4
  City: Menlo Park, USA | From $3250.00 to $4225.0
Row 31
  City: Seattle, USA | From $7100.00 to $9230.0
Row 32
Row 33
  City: Mountain View, USA | From $4000.00 to $5200.0
  City: Los Angeles, USA | From $11291.00 to $14678.3
Row 34
  City: Sunnyvale, USA | From $4320.00 to $5616.0
Row 35
  City: San Francisco, USA | From $3000.00 to $3900.0
Row 36
  City: San Francisco, USA | From $2560.00 to $3328.0
  City: San Francisco, USA | From $8000.00 to $10400.0
Row 37
  City: Los Angeles, USA | From $8500.00 to $11050.0
  City: Santa Clara, USA | From $6080.00 to $7904.0
  City: Menlo Park, USA | From $8400.00 to $10920.0
Row 38
  City: Venice, USA | From $11000.00 to $14300.0
Row 39
  City: San Francisco, USA | From $3825.00 to $4972.5
  City: Redwood City, USA | From $8000.00 to $10400.0
  City: Seattle, USA | From $11070.00 to $14391.0
Row 40
  City: San Bruno, USA | From $2400.00 to $3120.0
  City: Sunnyvale, USA | From $4000.00 to $5200.0
Row 41
  City: Santa Clara, USA | From $6200.00 to $8060.0
Row 42
  City: Seattle, USA | From $8500.00 to $11050.0
  City: San Francisco, USA | From $6250.00 to $8125.0
Row 43
  City: San Francisco, USA | From $6933.33 to $9013.329
  City: San Francisco, USA | From $6800.00 to $8840.0
Row 44
Row 45
  City: San Francisco, USA | From $6250.00 to $8125.0
  City: Seattle, USA | From $6455.00 to $8391.5
Row 46
  City: New York City, USA | From $6250.00 to $8125.0
  City: New York City, USA | From $8500.00 to $11050.0
Row 47
  City: Mountain View, USA | From $6400.00 to $8320.0
  City: Mountain View, USA | From $6600.00 to $8580.0
  City: Menlo Park, USA | From $9885.00 to $12850.5
Row 48
  City: Mountain View, USA | From $2500.00 to $3250.0
  City: Santa Clara, USA | From $8000.00 to $10400.0
Row 49
  City: Mountain View, USA | From $5867.00 to $7627.1
  City: New York City, USA | From $5000.00 to $6500.0
  City: San Francisco, USA | From $5800.00 to $7540.0
  City: Menlo Park, USA | From $0.00 to $0.0
Row 50
  City: New York City, USA | From $5500.00 to $7150.0
  City: San Francisco, USA | From $6900.00 to $8970.0
  City: Redwood City, USA | From $9725.00 to $12642.5
Row 51
  City: San Francisco, USA | From $8515.00 to $11069.5
  City: San Francisco, USA | From $6080.00 to $7904.0
  City: New York City, USA | From $6500.00 to $8450.0
Row 52
  City: San Francisco, USA | From $9000.00 to $11700.0
  City: Kirkland, USA | From $3680.00 to $4784.0
  City: Palo Alto, USA | From $8500.00 to $11050.0
Row 53
  City: San Francisco, USA | From $4000.00 to $5200.0
  City: San Francisco, USA | From $4500.00 to $5850.0
  City: New York City, USA | From $7000.00 to $9100.0
  City: Sunnyvale, USA | From $8500.00 to $11050.0
Row 54
  City: San Francisco, USA | From $8000.00 to $10400.0
  City: San Francisco, USA | From $7500.00 to $9750.0
  City: Menlo Park, USA | From $13530.00 to $17589.0
Row 55
  City: Palo Alto, USA | From $5000.00 to $6500.0
  City: Toronto, USA | From $10500.00 to $13650.0
  City: San Francisco, USA | From $8540.00 to $11102.0
  City: New York City, USA | From $11475.00 to $14917.5
Row 56
  City: Mountain View, USA | From $7050.00 to $9165.0
  City: Bellevue, USA | From $4480.00 to $5824.0
  City: San Francisco, USA | From $3000.00 to $3900.0
  City: Sunnyvale, USA | From $7725.00 to $10042.5
Row 57
  City: Menlo Park, USA | From $4000.00 to $5200.0
  City: San Francisco, USA | From $8908.00 to $11580.4
Row 58
  City: San Francisco, USA | From $3600.00 to $4680.0
  City: Santa Clara, USA | From $8576.00 to $11148.8
  City: Seattle, USA | From $6600.00 to $8580.0
Row 59
  City: Mountain View, USA | From $6000.00 to $7800.0
  City: Redmond, USA | From $8500.00 to $11050.0
Row 60
  City: San Francisco, USA | From $2400.00 to $3120.0
  City: San Diego, USA | From $6600.00 to $8580.0
  City: San Francisco, USA | From $6220.00 to $8086.0
  City: Redmond, USA | From $8000.00 to $10400.0
Row 61
  City: Mountain View, USA | From $3000.00 to $3900.0
  City: Menlo Park, USA | From $7100.00 to $9230.0
  City: San Francisco, USA | From $8000.00 to $10400.0
  City: Menlo Park, USA | From $5120.00 to $6656.0
Row 62
  City: Menlo Park, USA | From $8500.00 to $11050.0
  City: Mountain View, USA | From $7360.00 to $9568.0
  City: Seattle, USA | From $5000.00 to $6500.0
Row 63
  City: San Francisco, USA | From $7500.00 to $9750.0
  City: Redmond, USA | From $3360.00 to $4368.0
  City: Sunnyvale, USA | From $8000.00 to $10400.0
  City: Menlo Park, USA | From $5833.00 to $7582.9
Row 64
  City: San Francisco, USA | From $3040.00 to $3952.0
  City: Venice, USA | From $7000.00 to $9100.0
  City: Menlo Park, USA | From $7700.00 to $10010.0
Row 65
  City: San Francisco, USA | From $2880.00 to $3744.0
  City: Cambridge, USA | From $4000.00 to $5200.0
  City: San Francisco, USA | From $1975.00 to $2567.5
  City: San Francisco, USA | From $0.00 to $0.0
Row 66
  City: San Francisco, USA | From $0.00 to $0.0
  City: New York City, USA | From $5000.00 to $6500.0
  City: Menlo Park, USA | From $2900.00 to $3770.0
Row 67
  City: Boston, USA | From $5800.00 to $7540.0
  City: San Francisco, USA | From $10000.00 to $13000.0
  City: San Francisco, USA | From $7000.00 to $9100.0
  City: Redwood City, USA | From $7725.00 to $10042.5
Row 68
  City: Venice, USA | From $5440.00 to $7072.0
  City: Bellevue, USA | From $8000.00 to $10400.0
  City: Menlo Park, USA | From $8000.00 to $10400.0
Row 69
  City: San Francisco, USA | From $3813.00 to $4956.9
  City: New York City, USA | From $3520.00 to $4576.0
  City: New York City, USA | From $6666.00 to $8665.8
  City: San Francisco, USA | From $10455.00 to $13591.5
Row 70
  City: San Francisco, USA | From $5450.00 to $7085.0
Row 71
  City: San Francisco, USA | From $3700.00 to $4810.0
  City: Redmond, USA | From $9062.00 to $11780.6

  City: Los Angeles, USA | From $4320.00 to $5616.0
  City: San Francisco, USA | From $5200.00 to $6760.0
Row 72
  City: New York City, USA | From $3200.00 to $4160.0
Row 73
  City: New York City, USA | From $7000.00 to $9100.0
Row 74
  City: San Francisco, USA | From $7200.00 to $9360.0
  City: Cambridge, USA | From $6500.00 to $8450.0
Row 75
  City: San Francisco, USA | From $3600.00 to $4680.0
  City: Sunnyvale, USA | From $4200.00 to $5460.0
  City: Redmond, USA | From $7680.00 to $9984.0
Row 76
  City: Redmond, USA | From $4480.00 to $5824.0
Row 77
  City: Mountain View, USA | From $3000.00 to $3900.0
  City: Sunnyvale, USA | From $4000.00 to $5200.0
  City: San Francisco, USA | From $8500.00 to $11050.0
Row 78
  City: Redwood City, USA | From $4000.00 to $5200.0
  City: San Francisco, USA | From $9500.00 to $12350.0
  City: Seattle, USA | From $9075.00 to $11797.5
Row 79
  City: San Francisco, USA | From $3520.00 to $4576.0
Row 80
  City: San Francisco, USA | From $7205.00 to $9366.5
  City: Venice, USA | From $9000.00 to $11700.0
  City: Sunnyvale, USA | From $8000.00 to $10400.0
Row 81
  City: Santa Clara, USA | From $4524.00 to $5881.2
  City: Sunnyvale, USA | From $7200.00 to $9360.0
Row 82
  City: Mountain View, USA | From $7205.00 to $9366.5
  City: Los Angeles, USA | From $7000.00 to $9100.0
Row 83
  City: Redmond, USA | From $9000.00 to $11700.0
Row 84
  City: New York City, USA | From $3800.00 to $4940.0
  City: San Francisco, USA | From $8916.00 to $11590.8
  City: Menlo Park, USA | From $5120.00 to $6656.0
Row 85
  City: Mountain View, USA | From $4000.00 to $5200.0
  City: Seattle, USA | From $0.00 to $0.0
  City: Santa Clara, USA | From $9380.00 to $12194.0
  City: Palo Alto, USA | From $9840.00 to $12792.0
Row 86
  City: Palo Alto, USA | From $7950.00 to $10335.0
Row 87
  City: Mountain View, USA | From $6000.00 to $7800.0
  City: Seattle, USA | From $9500.00 to $12350.0
Row 88
  City: Redwood City, USA | From $6080.00 to $7904.0
  City: Mountain View, USA | From $7660.00 to $9958.0
Row 89
  City: San Francisco, USA | From $8000.00 to $10400.0
  City: Seattle, USA | From $4800.00 to $6240.0
Row 90
  City: San Francisco, USA | From $4000.00 to $5200.0
  City: New York City, USA | From $5000.00 to $6500.0
  City: Los Altos, USA | From $3250.00 to $4225.0
Row 91
  City: Pittsburgh, USA | From $7500.00 to $9750.0
  City: San Francisco, USA | From $5600.00 to $7280.0
  City: San Francisco, USA | From $0.00 to $0.0
Row 92
  City: San Francisco, USA | From $13000.00 to $16900.0
Row 93
  City: San Francisco, USA | From $3200.00 to $4160.0
  City: San Francisco, USA | From $8000.00 to $10400.0
Row 94
  City: San Francisco, USA | From $2600.00 to $3380.0
  City: New York City, USA | From $3200.00 to $4160.0
  City: San Francisco, USA | From $8333.00 to $10832.9
Row 95
  City: San Francisco, USA | From $6060.00 to $7878.0
  City: Menlo Park, USA | From $0.00 to $0.0
Row 96
  City: San Francisco, USA | From $5500.00 to $7150.0
  City: San Francisco, USA | From $7600.00 to $9880.0
Row 97
  City: Seattle, USA | From $3200.00 to $4160.0
  City: Redmond, USA | From $5600.00 to $7280.0
  City: Menlo Park, USA | From $0.00 to $0.0
  City: Bellevue, USA | From $12000.00 to $15600.0
Row 98
  City: San Francisco, USA | From $8040.00 to $10452.0
  City: Menlo Park, USA | From $7200.00 to $9360.0
Row 99
  City: San Francisco, USA | From $6833.00 to $8882.9
  City: Menlo Park, USA | From $6400.00 to $8320.0
Row 100
  City: San Francisco, USA | From $9800.00 to $12740.0
  City: Menlo Park, USA | From $10100.00 to $13130.0
Row 101
  City: Sunnyvale, USA | From $6000.00 to $7800.0
  City: San Francisco, USA | From $12300.00 to $15990.0
Row 102
  City: New York City, USA | From $9380.00 to $12194.0
  City: Menlo Park, USA | From $8000.00 to $10400.0
Row 103
  City: San Francisco, USA | From $8500.00 to $11050.0
  City: Seattle, USA | From $8200.00 to $10660.0
Row 104
  City: Los Angeles, USA | From $14441.00 to $18773.3
  City: San Francisco, USA | From $8000.00 to $10400.0
Row 105
  City: Mountain View, USA | From $6500.00 to $8450.0
  City: Santa Clara, USA | From $11390.00 to $14807.0
  City: Menlo Park, USA | From $8000.00 to $10400.0
Row 106
  City: Cupertino, USA | From $8000.00 to $10400.0
  City: Bellevue, USA | From $15189.00 to $19745.7
Row 107
  City: San Francisco, USA | From $3360.00 to $4368.0
  City: San Francisco, USA | From $2960.00 to $3848.0
  City: Sunnyvale, USA | From $4480.00 to $5824.0
  City: New York City, USA | From $8777.00 to $11410.1
Row 108
Row 109
  City: Weston, USA | From $2800.00 to $3640.0
  City: San Francisco, USA | From $8500.00 to $11050.0
  City: Seattle, USA | From $8320.00 to $10816.0
  City: Seattle, USA | From $8000.00 to $10400.0
Row 110
  City: San Francisco, USA | From $10000.00 to $13000.0
Row 111
  City: San Francisco, USA | From $5600.00 to $7280.0
  City: New York City, USA | From $7200.00 to $9360.0
  City: New York City, USA | From $8700.00 to $11310.0
Row 112
  City: Boston, USA | From $4800.00 to $6240.0
  City: San Francisco, USA | From $6100.00 to $7930.0

In [120]:
df.to_csv('../private/results-currency-normalized.csv', index=False)