In [6]:
from IPython.display import display

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)
plt.style.use('ggplot')

# Show matplotlib plots in this notebook
%matplotlib inline
# Setting plot parameters
from pylab import rcParams
params = {
    'figure.figsize': (8, 8),
    'legend.fontsize': 15
}
rcParams.update(params)

In [7]:
df = pd.read_csv('../private/results-04-10.csv')  # TODO: Write the response file

EXCHANGE_RATE = [
    1.0874,
    1.2070,
    1.3901,
    1.3108,
    1.3653,
    1.2576
]

In [8]:
def get_cad_salary(salary, term):
    return float(salary) * EXCHANGE_RATE[term-1]

In [9]:
def is_invalid_salary(salary):
    if type(salary) == str:
        salary = salary.replace(',', '')
    try:
        float(salary)
        if salary < 100:
            return True
        return False
    except e:
        print('Exception', salary, str(e))
        return True

In [10]:
def isnan(a):
    return a != a

In [11]:
def isfloat(value):
  try:
    float(value)
    return not isnan(value)
  except ValueError:
    return False

In [13]:
for i in range(0, df.shape[0]):
    print('Row ' + str(i))
    for term in range(1, 7):
        if isnan(df['coop_loc_' + str(term)][i]) or 'USA' not in df['coop_loc_' + str(term)][i]:
            continue
        if is_invalid_salary(df['coop_salary_' + str(term)][i]):
            continue
        old = df['coop_salary_' + str(term)][i]
        if isnan(old):
            continue
            
        if not isfloat(old):
            old = old.replace(',', '')
        df.loc[i, 'coop_salary_' + str(term)] = get_cad_salary(old, term)
        print('  City: ' + df['coop_loc_' + str(term)][i] + 
              ' | From $' + str(old) + ' to $' + str(df['coop_salary_' + str(term)][i]))

Row 0
  City: Chicago, USA | From $10725.0 to $13942.5
  City: Mountain View, USA | From $15678.0 to $20381.4
  City: Chicago, USA | From $10400.0 to $13520.0
Row 1
  City: San Francisco, USA" | From $1622.4 to $2109.12
  City: Santa Clara, USA | From $14950.0 to $19435.0
Row 2
  City: Menlo Park, USA | From $8450.0 to $10985.0
  City: San Francisco, USA | From $6500.0 to $8450.0
  City: San Francisco, USA | From $10400.0 to $13520.0
Row 3
  City: Boston, USA | From $3900.0 to $5070.0
  City: San Mateo, USA | From $12350.0 to $16055.0
  City: Seattle, USA | From $6500.0 to $8450.0
Row 4
  City: San Francisco, USA | From $4160.0 to $5408.0
  City: San Francisco, USA | From $5200.0 to $6760.0
  City: Santa Clara, USA | From $11590.8 to $15068.04
  City: New York City, USA | From $3380.0 to $4394.0
  City: Seattle, USA | From $9295.0 to $12083.5
Row 5
  City: San Francisco, USA | From $5850.0 to $7605.0
Row 6
  City: Boston, USA | From $4550.0 to $5915.0
  City: Bellevue, USA | From $5460.0 to $7098.0
  City: Menlo Park, USA | From $14807.0 to $19249.1
  City: Sunnyvale, USA | From $12025.0 to $15632.5
Row 7
  City: San Mateo, USA | From $11375.0 to $14787.5
  City: San Francisco, USA | From $5850.0 to $7605.0
Row 8
  City: Foster City, USA | From $5200.0 to $6760.0
  City: San Francisco, USA | From $11069.5 to $14390.35
  City: New York City, USA | From $9568.0 to $12438.4
Row 9
  City: San Francisco, USA | From $9100.0 to $11830.0
  City: San Francisco, USA | From $10400.0 to $13520.0
Row 10
  City: San Francisco, USA | From $4550.0 to $5915.0
Row 11
  City: Mountain View, USA | From $3900.0 to $5070.0
  City: San Francisco, USA | From $13936.0 to $18116.8
  City: Seattle, USA | From $9360.0 to $12168.0
Row 12
  City: San Francisco, USA | From $4680.0 to $6084.0
  City: Seattle, USA | From $5850.0 to $7605.0
  City: San Francisco, USA | From $11700.0 to $15210.0
Row 13
  City: Weston, USA | From $3770.0 to $4901.0
  City: Menlo Park, USA | From $20280.0 to $26364.0
Row 14
  City: San Francisco, USA | From $12772.5 to $16604.25
  City: San Francisco, USA | From $10725.0 to $13942.5
  City: San Francisco, USA | From $8736.0 to $11356.8
Row 15
  City: San Francisco, USA | From $3640.0 to $4732.0
  City: San Francisco, USA | From $2600.0 to $3380.0
  City: San Francisco, USA | From $11700.0 to $15210.0
Row 16
  City: San Francisco, USA | From $3744.0 to $4867.2
  City: Santa Clara, USA | From $5824.0 to $7571.2
  City: Mountain View, USA | From $7426.25 to $9654.125
Row 17
  City: Venice, USA | From $8694.4 to $11302.72
  City: Mountain View, USA | From $10725.0 to $13942.5
Row 18
  City: San Francisco, USA | From $4550.0 to $5915.0
  City: San Francisco, USA | From $9100.0 to $11830.0
  City: San Francisco, USA | From $15190.5 to $19747.65
Row 19
  City: Palo Alto, USA | From $4160.0 to $5408.0
  City: San Francisco, USA | From $9490.0 to $12337.0
  City: Menlo Park, USA | From $8320.0 to $10816.0
Row 20
  City: Mountain View, USA | From $11050.0 to $14365.0
  City: San Francisco, USA | From $4420.0 to $5746.0
  City: San Francisco, USA | From $12820.6 to $16666.78
  City: Menlo Park, USA | From $9269.0 to $12049.7
Row 21
  City: San Francisco, USA | From $3250.0 to $4225.0
  City: San Francisco, USA | From $8320.0 to $10816.0
Row 22
  City: Toronto, USA | From $8320.0 to $10816.0
Row 23
  City: San Francisco, USA | From $5460.0 to $7098.0
  City: San Francisco, USA | From $8580.0 to $11154.0
  City: San Francisco, USA | From $13936.0 to $18116.8
  City: New York City, USA | From $9750.0 to $12675.0
Row 24
  City: San Mateo, USA | From $11700.0 to $15210.0
  City: San Francisco, USA | From $9360.0 to $12168.0
Row 25
  City: San Francisco, USA | From $7663.5 to $9962.55
  City: Menlo Park, USA | From $7215.0 to $9379.5
  City: Sunnyvale, USA | From $10400.0 to $13520.0
Row 26
  City: Seattle, USA | From $9360.0 to $12168.0
Row 27
  City: San Mateo, USA | From $7800.0 to $10140.0
  City: Menlo Park, USA | From $6500.0 to $8450.0
Row 28
  City: Sunnyvale, USA | From $12886.9 to $16752.97
Row 29
  City: Menlo Park, USA | From $14004.9 to $18206.37
  City: Redmond, USA | From $7904.0 to $10275.2
Row 30
  City: San Francisco, USA | From $14284.4 to $18569.72
  City: Menlo Park, USA | From $4225.0 to $5492.5
Row 31
  City: Seattle, USA | From $9230.0 to $11999.0
Row 32
Row 33
  City: Mountain View, USA | From $5200.0 to $6760.0
  City: Los Angeles, USA | From $14678.3 to $19081.79
Row 34
  City: Sunnyvale, USA | From $5616.0 to $7300.8
Row 35
  City: San Francisco, USA | From $3900.0 to $5070.0
Row 36
  City: San Francisco, USA | From $3328.0 to $4326.4
  City: San Francisco, USA | From $10400.0 to $13520.0
Row 37
  City: Los Angeles, USA | From $11050.0 to $14365.0
  City: Santa Clara, USA | From $7904.0 to $10275.2
  City: Menlo Park, USA | From $10920.0 to $14196.0
Row 38
  City: Venice, USA | From $14300.0 to $18590.0
Row 39
  City: San Francisco, USA | From $4972.5 to $6464.25
  City: Redwood City, USA | From $10400.0 to $13520.0
  City: Seattle, USA | From $14391.0 to $18708.3
Row 40
  City: San Bruno, USA | From $3120.0 to $4056.0
  City: Sunnyvale, USA | From $5200.0 to $6760.0
Row 41
  City: Santa Clara, USA | From $8060.0 to $10478.0
Row 42
  City: Seattle, USA | From $11050.0 to $14365.0
  City: San Francisco, USA | From $8125.0 to $10562.5
Row 43
  City: San Francisco, USA | From $9013.329 to $11717.3277
  City: San Francisco, USA | From $8840.0 to $11492.0
Row 44
Row 45
  City: San Francisco, USA | From $8125.0 to $10562.5
  City: Seattle, USA | From $8391.5 to $10908.95
Row 46
  City: New York City, USA | From $8125.0 to $10562.5
  City: New York City, USA | From $11050.0 to $14365.0
Row 47
  City: Mountain View, USA | From $8320.0 to $10816.0
  City: Mountain View, USA | From $8580.0 to $11154.0
  City: Menlo Park, USA | From $12850.5 to $16705.65
Row 48
  City: Mountain View, USA | From $3250.0 to $4225.0
  City: Santa Clara, USA | From $10400.0 to $13520.0
Row 49
  City: Mountain View, USA | From $7627.1 to $9915.23
  City: New York City, USA | From $6500.0 to $8450.0
  City: San Francisco, USA | From $7540.0 to $9802.0
Row 50
  City: New York City, USA | From $7150.0 to $9295.0
  City: San Francisco, USA | From $8970.0 to $11661.0
  City: Redwood City, USA | From $12642.5 to $16435.25
Row 51
  City: San Francisco, USA | From $11069.5 to $14390.35
  City: San Francisco, USA | From $7904.0 to $10275.2
  City: New York City, USA | From $8450.0 to $10985.0
Row 52
  City: San Francisco, USA | From $11700.0 to $15210.0
  City: Kirkland, USA | From $4784.0 to $6219.2
  City: Palo Alto, USA | From $11050.0 to $14365.0
Row 53
  City: San Francisco, USA | From $5200.0 to $6760.0
  City: San Francisco, USA | From $5850.0 to $7605.0
  City: New York City, USA | From $9100.0 to $11830.0
  City: Sunnyvale, USA | From $11050.0 to $14365.0
Row 54
  City: San Francisco, USA | From $10400.0 to $13520.0
  City: San Francisco, USA | From $9750.0 to $12675.0
  City: Menlo Park, USA | From $17589.0 to $22865.7
Row 55
  City: Palo Alto, USA | From $6500.0 to $8450.0
  City: Toronto, USA | From $13650.0 to $17745.0
  City: San Francisco, USA | From $11102.0 to $14432.6
  City: New York City, USA | From $14917.5 to $19392.75
Row 56
  City: Mountain View, USA | From $9165.0 to $11914.5
  City: Bellevue, USA | From $5824.0 to $7571.2
  City: San Francisco, USA | From $3900.0 to $5070.0
  City: Sunnyvale, USA | From $10042.5 to $13055.25
Row 57
  City: Menlo Park, USA | From $5200.0 to $6760.0
  City: San Francisco, USA | From $11580.4 to $15054.52
Row 58
  City: San Francisco, USA | From $4680.0 to $6084.0
  City: Santa Clara, USA | From $11148.8 to $14493.44
  City: Seattle, USA | From $8580.0 to $11154.0
Row 59
  City: Mountain View, USA | From $7800.0 to $10140.0
  City: Redmond, USA | From $11050.0 to $14365.0
Row 60
  City: San Francisco, USA | From $3120.0 to $4056.0
  City: San Diego, USA | From $8580.0 to $11154.0
  City: San Francisco, USA | From $8086.0 to $10511.8
  City: Redmond, USA | From $10400.0 to $13520.0
Row 61
  City: Mountain View, USA | From $3900.0 to $5070.0
  City: Menlo Park, USA | From $9230.0 to $11999.0
  City: San Francisco, USA | From $10400.0 to $13520.0
  City: Menlo Park, USA | From $6656.0 to $8652.8
Row 62
  City: Menlo Park, USA | From $11050.0 to $14365.0
  City: Mountain View, USA | From $9568.0 to $12438.4
  City: Seattle, USA | From $6500.0 to $8450.0
Row 63
  City: San Francisco, USA | From $9750.0 to $12675.0
  City: Redmond, USA | From $4368.0 to $5678.4
  City: Sunnyvale, USA | From $10400.0 to $13520.0
  City: Menlo Park, USA | From $7582.9 to $9857.77
Row 64
  City: San Francisco, USA | From $3952.0 to $5137.6
  City: Venice, USA | From $9100.0 to $11830.0
  City: Menlo Park, USA | From $10010.0 to $13013.0
Row 65
  City: San Francisco, USA | From $3744.0 to $4867.2
  City: Cambridge, USA | From $5200.0 to $6760.0
  City: San Francisco, USA | From $2567.5 to $3337.75
Row 66
  City: New York City, USA | From $6500.0 to $8450.0
  City: Menlo Park, USA | From $3770.0 to $4901.0
Row 67
  City: Boston, USA | From $7540.0 to $9802.0
  City: San Francisco, USA | From $13000.0 to $16900.0
  City: San Francisco, USA | From $9100.0 to $11830.0
  City: Redwood City, USA | From $10042.5 to $13055.25
Row 68
  City: Venice, USA | From $7072.0 to $9193.6
  City: Bellevue, USA | From $10400.0 to $13520.0
  City: Menlo Park, USA | From $10400.0 to $13520.0
Row 69
  City: San Francisco, USA | From $4956.9 to $6443.97
  City: New York City, USA | From $4576.0 to $5948.8
  City: New York City, USA | From $8665.8 to $11265.54
  City: San Francisco, USA | From $13591.5 to $17668.95
Row 70
  City: San Francisco, USA | From $7085.0 to $9210.5
Row 71
  City: San Francisco, USA | From $4810.0 to $6253.0
  City: Redmond, USA | From $11780.6 to $15314.78
  City: Los Angeles, USA | From $5616.0 to $7300.8
  City: San Francisco, USA | From $6760.0 to $8788.0
Row 72
  City: New York City, USA | From $4160.0 to $5408.0
Row 73
  City: New York City, USA | From $9100.0 to $11830.0
Row 74
  City: San Francisco, USA | From $9360.0 to $12168.0
  City: Cambridge, USA | From $8450.0 to $10985.0
Row 75
  City: San Francisco, USA | From $4680.0 to $6084.0
  City: Sunnyvale, USA | From $5460.0 to $7098.0
  City: Redmond, USA | From $9984.0 to $12979.2
Row 76
  City: Redmond, USA | From $5824.0 to $7571.2
Row 77
  City: Mountain View, USA | From $3900.0 to $5070.0
  City: Sunnyvale, USA | From $5200.0 to $6760.0
  City: San Francisco, USA | From $11050.0 to $14365.0
Row 78
  City: Redwood City, USA | From $5200.0 to $6760.0
  City: San Francisco, USA | From $12350.0 to $16055.0
  City: Seattle, USA | From $11797.5 to $15336.75
Row 79
  City: San Francisco, USA | From $4576.0 to $5948.8
Row 80
  City: San Francisco, USA | From $9366.5 to $12176.45
  City: Venice, USA | From $11700.0 to $15210.0
  City: Sunnyvale, USA | From $10400.0 to $13520.0
Row 81

  City: Santa Clara, USA | From $5881.2 to $7645.56
  City: Sunnyvale, USA | From $9360.0 to $12168.0
Row 82
  City: Mountain View, USA | From $9366.5 to $12176.45
  City: Los Angeles, USA | From $9100.0 to $11830.0
Row 83
  City: Redmond, USA | From $11700.0 to $15210.0
Row 84
  City: New York City, USA | From $4940.0 to $6422.0
  City: San Francisco, USA | From $11590.8 to $15068.04
  City: Menlo Park, USA | From $6656.0 to $8652.8
Row 85
  City: Mountain View, USA | From $5200.0 to $6760.0
  City: Santa Clara, USA | From $12194.0 to $15852.2
  City: Palo Alto, USA | From $12792.0 to $16629.6
Row 86
  City: Palo Alto, USA | From $10335.0 to $13435.5
Row 87
  City: Mountain View, USA | From $7800.0 to $10140.0
  City: Seattle, USA | From $12350.0 to $16055.0
Row 88
  City: Redwood City, USA | From $7904.0 to $10275.2
  City: Mountain View, USA | From $9958.0 to $12945.4
Row 89
  City: San Francisco, USA | From $10400.0 to $13520.0
  City: Seattle, USA | From $6240.0 to $8112.0
Row 90
  City: San Francisco, USA | From $5200.0 to $6760.0
  City: New York City, USA | From $6500.0 to $8450.0
  City: Los Altos, USA | From $4225.0 to $5492.5
Row 91
  City: Pittsburgh, USA | From $9750.0 to $12675.0
  City: San Francisco, USA | From $7280.0 to $9464.0
Row 92
  City: San Francisco, USA | From $16900.0 to $21970.0
Row 93
  City: San Francisco, USA | From $4160.0 to $5408.0
  City: San Francisco, USA | From $10400.0 to $13520.0
Row 94
  City: San Francisco, USA | From $3380.0 to $4394.0
  City: New York City, USA | From $4160.0 to $5408.0
  City: San Francisco, USA | From $10832.9 to $14082.77
Row 95
  City: San Francisco, USA | From $7878.0 to $10241.4
Row 96
  City: San Francisco, USA | From $7150.0 to $9295.0
  City: San Francisco, USA | From $9880.0 to $12844.0
Row 97
  City: Seattle, USA | From $4160.0 to $5408.0
  City: Redmond, USA | From $7280.0 to $9464.0
  City: Bellevue, USA | From $15600.0 to $20280.0
Row 98
  City: San Francisco, USA | From $10452.0 to $13587.6
  City: Menlo Park, USA | From $9360.0 to $12168.0
Row 99
  City: San Francisco, USA | From $8882.9 to $11547.77
  City: Menlo Park, USA | From $8320.0 to $10816.0
Row 100
  City: San Francisco, USA | From $12740.0 to $16562.0
  City: Menlo Park, USA | From $13130.0 to $17069.0
Row 101
  City: Sunnyvale, USA | From $7800.0 to $10140.0
  City: San Francisco, USA | From $15990.0 to $20787.0
Row 102
  City: New York City, USA | From $12194.0 to $15852.2
  City: Menlo Park, USA | From $10400.0 to $13520.0
Row 103
  City: San Francisco, USA | From $11050.0 to $14365.0
  City: Seattle, USA | From $10660.0 to $13858.0
Row 104
  City: Los Angeles, USA | From $18773.3 to $24405.29
  City: San Francisco, USA | From $10400.0 to $13520.0
Row 105
  City: Mountain View, USA | From $8450.0 to $10985.0
  City: Santa Clara, USA | From $14807.0 to $19249.1
  City: Menlo Park, USA | From $10400.0 to $13520.0
Row 106
  City: Cupertino, USA | From $10400.0 to $13520.0
  City: Bellevue, USA | From $19745.7 to $25669.41
Row 107
  City: San Francisco, USA | From $4368.0 to $5678.4
  City: San Francisco, USA | From $3848.0 to $5002.4
  City: Sunnyvale, USA | From $5824.0 to $7571.2
  City: New York City, USA | From $11410.1 to $14833.13
Row 108
Row 109
  City: Weston, USA | From $3640.0 to $4732.0
  City: San Francisco, USA | From $11050.0 to $14365.0
  City: Seattle, USA | From $10816.0 to $14060.8
  City: Seattle, USA | From $10400.0 to $13520.0
Row 110
  City: San Francisco, USA | From $13000.0 to $16900.0
Row 111
  City: San Francisco, USA | From $7280.0 to $9464.0
  City: New York City, USA | From $9360.0 to $12168.0
  City: New York City, USA | From $11310.0 to $14703.0
Row 112
  City: Boston, USA | From $6240.0 to $8112.0
  City: San Francisco, USA | From $7930.0 to $10309.0

In [120]:
df.to_csv('../private/results-currency-normalized.csv', index=False)